### ISSUE TITLE
Computation of Cramer Coefficient

### ISSUE THREAD

**Issue by felixcremer** [johncwok/CategoricalTimeSeries.jl#5]
When I compare the results you get with the Figure 6.4 in C. Weiss I see  a similar pattern for the Cohen coefficient, but for the Cramer coefficient we have a different pattern. 

![image](https://user-images.githubusercontent.com/17124431/138904845-146bc774-8f96-4bc3-a1d6-6033a386a644.png)

I am not sure, whether this is related, In this line of the cramer_coefficient function I suppose you wanted to write `+=` instead of `=+`

https://github.com/johncwok/CategoricalTimeSeries.jl/blob/01c05c8db6e3127639fecd0f41040046629c5d8e/src/SerialDependence.jl#L160

Otherwise you wouldn't need the for loop.

**Comment by CNelias** [comment]
You are right this is what caused the issue. Thanks for pointing that out I didn't notice it.
Also, this was also there in the ```cohen_coefficient``` function, but only in the normalization constant which is why the shape wasn't affected. I fixed all of these, made a new release and re-registered so the correct version will be online soon.
